### ISSUE TITLE
Manage I18N of date

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/Website-Volontaria#21]
## Expected behavior
I want to be able to display a full date in French on the website
Ex: `12 Janvier 2018`

## Current behavior
Actually i can only display date in English
Ex : `12 January 2018`

## Potential solution
Say me ;)

**Comment by francisjeanneau** [comment]
Don't you think the API should handle this?

**Comment by RignonNoel** [comment]
Actually we take a standard format like this one from the API : `2015-10-22T19:50:08`
It's good because all system can work with him and it's pretty clear for developer.

In Angular we use a standard object `Date` who allow use to format the date in a human readable one, but it's just in english. It's why i think it's on the Angular side we need to translate to display in the good language.

**Comment by francisjeanneau** [comment]
Fair enough! It could be inlcuded in the front-end's traduction system.
