### ISSUE TITLE
Event unsubscription confirmation

### ISSUE THREAD

**Issue by francisjeanneau** [Volontaria/Website-Volontaria#32]
## Expected behaviour
I should get a confirmation message reassuring me when I unsubscribe from an event.

## Current behavior
When the "unsubscribe button is pressed, the prticipation is immediatly removed. 

## Potential solution
Create a simple confirm dialog that explains what is going to happen if you press "confirm"

**Comment by RignonNoel** [comment]
https://genielibre.com/issues/25
